### ISSUE TITLE
Make text sloppy to avoid hyphenation

### ISSUE THREAD

**Issue by omarz1** [ypid/latex-packages#14]
Hello. How about you make the text next to the license logo `\sloppy` to avoid hyphenation? I think hyphenating the text over such a small space doesn't look nice.

**Comment by ypid** [comment]
Nice idea :+1: I agree that avoiding hyphenating for `\doclicenseThis` looks better. I am going to use `\RaggedLeft` from [ragged2e](https://ctan.org/pkg/ragged2e] and `\raggedright` and make it configurable via package options (probably defaulting to `\RaggedLeft`).

**Comment by omarz1** [comment]
That's even better :)

**Comment by ypid** [comment]
I just added support as described above. Can you test it and give me feedback if that is what you had in mind?

I think there is still room for improvement. For example, the minipage environment is currently setup using fixed values. If there was a way to let TeX stretch the boundaries of this environment to help find the optimal width I would assume that this would also allow to eliminate most hyphenations while still typesetting `\doclicenseLongText` as justified text (assuming that has been set as default for normal text).

**Comment by omarz1** [comment]
Sure. I'll check it tomorrow. I appreciate your efforts.

**Comment by ypid** [comment]
Did you find the time? I have no problem in waiting with the release a few days more when you want to give it a try before that.

**Comment by omarz1** [comment]
I'm so sorry @ypid, I've been really busy last week. I haven't even downloaded it. Do I need to download the whole thing or just the `sty` file?

**Comment by ypid** [comment]
@omarz1 Don’t worry :wink: The `sty` will do. https://github.com/ypid/latex-packages/blob/master/doclicense/doclicense.sty

**Comment by omarz1** [comment]
OK. I just tested it and I'm still getting hyphenation over the word international.
MWE:
```
\documentclass{article}
\usepackage{hyperref}
\usepackage[
    type={CC},
    modifier={by-nc-sa},
    version={4.0},
]{doclicense}
\begin{document}
\doclicenseThis
\end{document}
```
Output:
![untitled3](https://cloud.githubusercontent.com/assets/7592333/14720607/f1fccf38-080a-11e6-961a-5e559f2b4fa7.png)

**Comment by ypid** [comment]
@omarz1 That was the expected behavior as documented. You can use `hyphenation={raggedright}` to force TeX not to make hyphenations (which I expected would look worse). But after testing this a bit more, I am not sure if I should enable this feature by default as it might look worse then just hyphenating one word. So I guess either `\raggedright` or leaving it as is (defaulting to justified text). What do you think and do you have a better solution for this? See also [my previous comment](https://github.com/ypid/latex-packages/issues/14#issuecomment-208593414).

Lets compare.

```LaTeX
\documentclass{article}
\usepackage[
  hidelinks,
]{hyperref}
\usepackage[
  type={CC},
  modifier={by-nc-sa},
  version={4.0},
  hyphenation={},
  % hyphenation={raggedright},
]{doclicense}
\begin{document}
\doclicenseThis%
\end{document}
```

![justified](https://cloud.githubusercontent.com/assets/1301158/14724545/3ce84f98-0817-11e6-970b-a0200be63913.png)

---

```LaTeX
  % hyphenation={},
  % hyphenation={raggedright},
```
![min_hyphen](https://cloud.githubusercontent.com/assets/1301158/14724635/bda7c0f0-0817-11e6-9757-21403ac16d73.png)

---



```LaTeX
  % hyphenation={},
  hyphenation={raggedright},
```
![no_hyph](https://cloud.githubusercontent.com/assets/1301158/14724551/408ec9ba-0817-11e6-8ead-2446288198fd.png)

**Comment by omarz1** [comment]
It is excellent that you have that as an option. I say you leave it exactly like in your test. So by default it shouldn't be enabled, just because it might make it look worse.

**Comment by ypid** [comment]
Thanks for you feedback. So I currently don’t enable this feature by default but I did use `RaggedRight` for the documentation PDF because it avoids additional white space between words in the first line. I am going to make a release tomorrow.
