### ISSUE TITLE
Incompatibility with biblatex/csquotes

### ISSUE THREAD

**Issue by IlarioBonacina** [ypid/latex-packages#35]
When this package is loaded together with bib latex it produces two errors.
Example code:
\documentclass{article}
\usepackage{biblatex}
\usepackage{doclicense}

\begin{document}
\end{document}

When loaded as 
\documentclass{article}
\usepackage{csquotes}
\usepackage{biblatex}
\usepackage{doclicense}

\begin{document}
\end{document}
the error seems to disappear.

**Comment by ypid** [comment]
Thanks for reporting! I did not find an easy way to work around this error because `\enquote` is defined by biblatex when biblatex detects that `\enquote` is not defined yet. I don’t really want to use `\enquote` when it is defined by a package other than csquotes for robustness reasons. So the best I can do is to detect this issue and give a better error text to the user in the hope that this helps to troubleshoot and solve the issue faster.

Does this work for you? Feel free to try the [fixed doclicense.sty file](https://github.com/ypid/latex-packages/blob/master/doclicense/doclicense.sty) and report back. I will wait a bit with releasing this fix to CTAN/TeXLive.
