### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by jotagah** [ypid/latex-packages#66]
Greetings!

Today, after your last update (Sept, 19), I got an error message when compiling the same latex file I compiled with success before (using tufte-handout template): 

"! Undefined control sequence. <argument> \hyxmp@dc@langs"

that seems is due the new default loaded hyperxmp style: (from VS Code):

{
	"resource": "/usr/local/texlive/2020/texmf-dist/tex/latex/hyperxmp/hyperxmp.sty",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Undefined control sequence.\n<argument> \\hyxmp@detect@langs \n",
	"source": "LaTeX",
	"startLineNumber": 407,
	"startColumn": 1,
	"endLineNumber": 407,
	"endColumn": 65536
}

In my preamble I have:

\usepackage[brazilian]{babel}
usepackage[
    type={CC},
    modifier={by-nc-nd},
    version={3.0},
]{doclicense}

Best,

J.

**Comment by ypid** [comment]
Hi, thank you for testing and reporting this so quickly after the release! I am able to reproduce this with the latest `hyperxmp` package version. Old versions still work fine (from TeX Live 2018 from Debian buster) that is why I did not notice it. I probably need a better test matrix, tracked in #67.

The issue seems to be the order in which I load the hyperxmp package related to the `\hypersetup` call. `hyperxmp` docs:

> To use hyperxmp, merely put a \textbackslash usepackage\{hyperxmp\} in your document's preamble. That line can appear anywhere before the hyperref pdf options are specified (i.e., with either \textbackslash usepackage[. . . ]\{hyperref\} or \textbackslash hypersetup\{. . . \}).

But I don’t have a fully working patch ready. Hopefully within the next days so that you can test it and I can release this as hot fix to CTAN.

**Comment by jotagah** [comment]
Hello ypid,

Unfortunatelly I got the same error: 

Undefined control sequence.
<argument> \hyxmp@dc@lang 

I downloaded your new release (2020/09/18 v2.2.1.dev) and unzipped it to my local texmf directory. An excerpt from \listfiles:

...
doclicense.sty    2020/09/18 v2.2.1.dev Support for putting documents under a license
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
doclicense-brazilian.ldf    
 ccicons.sty    2017/10/30 v1.6 LaTeX support for Creative Commons icons
hyperxmp.sty    2020/06/19 v5.4 Store hyperref metadata in XMP format
...

Best,

J.

**Comment by ypid** [comment]
My bad, you probably downloaded the master branch. I also pushed the post-release version bump to this branch. It does not have the fix yet. Try https://github.com/ypid/latex-packages/archive/fix-66.zip

**Comment by jotagah** [comment]
Hello.

Well, last time I downloaded the same version number you sent attached for me. 

I unzipped it and compiled with the same error message:

Undefined control sequence.
<argument> \hyxmp@dc@lang 

With \listfiles I got:

doclicense.sty    2020/09/18 v2.2.1.dev Support for putting documents under a license
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
doclicense-brazilian.ldf    
 ccicons.sty    2017/10/30 v1.6 LaTeX support for Creative Commons icons
hyperxmp.sty    2020/06/19 v5.4 Store hyperref metadata in XMP format

After deleted your new release all works again, and, from \listfiles:

doclicense.sty    2020/07/26 v2.1.0 Support for putting documents under a license
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
doclicense-brazilian.ldf    
 ccicons.sty    2017/10/30 v1.6 LaTeX support for Creative Commons icons

I also tested loading the hyperxmp package just before your doclicense, and there was no errors. From \listfiles:

hyperxmp.sty    2020/06/19 v5.4 Store hyperref metadata in XMP format
 ifdraft.sty    2016/05/16 v1.4 Detect class options draft and final (HO)
doclicense.sty    2020/07/26 v2.1.0 Support for putting documents under a license
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
doclicense-brazilian.ldf    
babel-brazilian.tex
babel-portuguese-brazil.tex
 ccicons.sty    2017/10/30 v1.6 LaTeX support for Creative Commons icons

[ ]’s,

J.

**Comment by ypid** [comment]
Thanks for testing. I dug deeper into it and read one relevant part of the hyperxmp implementation and I think I understand the issue now. I updated #66. You may test the zip file again.

Details:

Load order must be precise because hyperxmp also installs a hook with \AtEndPreamble same as we do. Now our hook needs to be executed before then one of hyperxmp because hyperxmp checks if hyperref is loaded and if it does not at the point where hyperxmp checks, it will do nothing.

Worth noting that hyperref should be loaded as one of the last packages. That is one of the reasons I do this trick with `\AtEndPreamble`.

**Comment by jotagah** [comment]
Greetings,

You fixed it. Congratulations

And thanks.

J.

**Comment by ypid** [comment]
Thanks to you :) I released it to CTAN just now.
